week2
Maximillian21/pschool pull request #2
Opened 2021-10-31 19:04 UTC by Maximillian21

2021-11-01 10:15 UTC, debuggerUA requested changes
В целом хорошо, пару моментов нужно исправить.

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/AndroidManifest.xml
> +            android:exported="true">
Для чего установлен этот флаг?

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
Для чего установлен этот флаг?

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/java/com/example/photosearch/viewmodels/MainViewModel.kt
> +                    Log.d("error", response.message())
```suggestion
                    Log.d("error", response.message())
                    loading.value = false
```

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/java/com/example/photosearch/viewmodels/MainViewModel.kt
> +                    Log.d("result", "success")
В качестве тегов для лога лучше указывать класс, который его вызывает. Помогает в поиске по логам.

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/java/com/example/photosearch/views/MainActivity.kt
> +    private fun createLinksString(linksList: List<Photo>): Spannable {
Я бы перенёс это в ViewModel и обсёрвил напрямую результат работы этой функции. Таким образом мы убираем из Активити код, относящийся к преобразованию данных.
И, что более важно, этот код работает в UI потоке.

2021-11-01 10:15 UTC, debuggerUA commented on app/src/main/java/com/example/photosearch/views/MainActivity.kt
> +    private val DOMAIN_NAME = "www.flickr.com/photos/"
Нарушение принципа [**DRY**](https://uk.wikipedia.org/wiki/Don%27t_repeat_yourself)
У тебя уже есть эти данные в другом месте, переиспользуй.

2021-11-01 14:29 UTC, Maximillian21 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true">
Используется для отправки данных в активити из других приложений. Остался после того, как пробовал открывать ссылки другим способом, не уследил

2021-11-01 14:29 UTC, Maximillian21 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
Используется для отправки данных в активити из других приложений. Остался после того, как пробовал открывать ссылки другим способом, не уследил

2021-11-01 18:58 UTC, Maximillian21 commented on app/src/main/java/com/example/photosearch/viewmodels/MainViewModel.kt
> +    suspend fun createLinksString(linksList: List<Photo>, context: Context, bundle: Bundle?) =
Функция перенесена во viewmodel, сделана асинхронной, но появился баг - ссылки в списке работают только после второго и более нажатия на кнопку Find. Первый список результатов теряет onClick

2021-11-11 09:37 UTC, debuggerUA approved these changes

2021-11-11 10:50 UTC, merged